import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/ui/LayoutWrapper";
import { fetchMetaAndScripts } from "@/lib/settings"; // Adjust path as needed

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const metaScripts = await fetchMetaAndScripts();

  return (
    <html lang="en">
      <head>
        <title>{metaScripts?.metaTitle || "Default Title"}</title>
        <meta
          name="description"
          content={metaScripts?.metaDescription || "Default description"}
        />

        {/* Google Tags */}
        {metaScripts?.googleAnalytics && (
          <script
            dangerouslySetInnerHTML={{ __html: metaScripts.googleAnalytics }}
          />
        )}
        {metaScripts?.googleSearchConsole && (
          <meta
            name="google-site-verification"
            content={metaScripts.googleSearchConsole}
          />
        )}
        {metaScripts?.googleAdsense && (
          <script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${metaScripts.googleAdsense}`}
            crossOrigin="anonymous"
          ></script>
        )}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
